%YAML:1.0

# Topic name in rosbag
PointCloudTopic: "/lidar_pointcloud"
ImageTopic: "/camera_0/image"

# Lidar Data type(custom msg or pointcloud2)
Data.custom_msg:  0
# Initial extrinsic (usually provided by hand measurement or cad design)

ExtrinsicMat: !!opencv-matrix
  rows: 4
  cols: 4
  dt: d
  data: [0.0,   -1.0,  0.0,   0.0,
         1.0,   0.0,   0.0,    0.0,
         0.0,   0.0,   1.0,    0.0,
         0.0,   0.0,   0.0,    1.0]
# Params for Canny Edge Extraction

Canny.gray_threshold: 10
Canny.len_threshold: 100

# Params for Voxel Cutting & Plane Fitting & Edge Extraction
Voxel.size: 0.5
Voxel.down_sample_size: 0.02
Plane.min_points_size: 30
Plane.normal_theta_min: 30
Plane.normal_theta_max: 150
Plane.max_size: 8
Ransac.dis_threshold: 0.015
Edge.min_dis_threshold: 0.03
Edge.max_dis_threshold: 0.05
AdjustEuler1: -2
AdjustEuler2: -0.5
AdjustEuler3: 2

# Params for color point clouds
Color.dense: 0.1
Color.intensity_threshold: 5
